<?php

namespace App\Util;

class Constants
{
    const REGISTER_FB_FAILURE_NOT_ALLOWED = 'REGISTER_FB_FAILURE_NOT_ALLOWED';
    const REGISTER_FB_FAILURE_EMAIL_NOT_PROVIDED = 'REGISTER_FB_FAILURE_EMAIL_NOT_PROVIDED';
}
